apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: demo-cluster
  region: us-east-2
  version: "1.20"
vpc:
  cidr: 10.0.0.0/16
  nat:
    gateway: Single
  clusterEndpoints:
    publicAccess: true
    privateAccess: true
managedNodeGroups:
  - name: worker
    instanceType: "t3a.medium"
    minSize: 1
    maxSize: 5
    desiredCapacity: 1
    volumeSize: 50
    volumeEncrypted: true
    privateNetworking: true
    iam:
      withAddonPolicies:
        efs: true
        autoScaler: true
        albIngress: true
        cloudWatch: true
    tags:
      environment: Test
    ssh:
      enableSsm: true